# Generated by Django 5.0.2 on 2024-08-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.TextField(blank=True, default='username', max_length=50),
        ),
    ]
